# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-01 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_name', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('cust_type', models.CharField(blank=True, max_length=500, null=True)),
                ('cust_phone', models.CharField(blank=True, max_length=500, null=True)),
                ('cust_email', models.CharField(blank=True, max_length=500, null=True)),
                ('cust_gstin', models.CharField(blank=True, max_length=500, null=True)),
                ('cust_pan', models.CharField(blank=True, max_length=500, null=True)),
                ('cust_tin', models.CharField(blank=True, max_length=500, null=True)),
                ('cust_vat', models.CharField(blank=True, max_length=500, null=True)),
                ('cust_website', models.CharField(blank=True, max_length=500, null=True)),
                ('cust_sez', models.CharField(blank=True, max_length=500, null=True)),
                ('cust_company_address', models.CharField(blank=True, max_length=500, null=True)),
                ('cust_country', models.CharField(blank=True, max_length=500, null=True)),
                ('cust_state', models.CharField(blank=True, max_length=500, null=True)),
                ('cust_city', models.CharField(blank=True, max_length=500, null=True)),
                ('cust_pincode', models.CharField(blank=True, max_length=500, null=True)),
                ('cust_shipping_address', models.CharField(blank=True, max_length=500, null=True)),
                ('cust_shiiping_country', models.CharField(blank=True, max_length=500, null=True)),
                ('cust_shipping_state', models.CharField(blank=True, max_length=500, null=True)),
                ('cust_shipping_city', models.CharField(blank=True, max_length=500, null=True)),
                ('cust_shipping_pincode', models.CharField(blank=True, max_length=500, null=True)),
                ('cust_shipping_gstin', models.CharField(blank=True, max_length=500, null=True)),
                ('cust_facebook', models.CharField(blank=True, max_length=500, null=True)),
                ('cust_lst', models.CharField(blank=True, max_length=500, null=True)),
                ('cust_cst', models.CharField(blank=True, max_length=500, null=True)),
                ('cust_service_tax_no', models.CharField(blank=True, max_length=500, null=True)),
                ('cust_notes', models.TextField(blank=True, null=True)),
                ('cust_last_contacted', models.DateField(blank=True, max_length=500, null=True)),
                ('cust_upcoming_appointment', models.DateField(blank=True, max_length=500, null=True)),
                ('cust_followup_no', models.CharField(blank=True, max_length=500, null=True)),
                ('cust_contact', models.ManyToManyField(to='dashboard.Contact')),
            ],
        ),
    ]
