# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-01 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20181201_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_name', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('prod_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('prod_quantity', models.CharField(blank=True, max_length=500, null=True)),
                ('prod_unit', models.CharField(blank=True, max_length=500, null=True)),
                ('prod_tax', models.CharField(blank=True, max_length=500, null=True)),
                ('prod_hsn', models.CharField(blank=True, max_length=500, null=True)),
                ('sales_unit_price', models.CharField(blank=True, max_length=500, null=True)),
                ('sales_currency', models.CharField(blank=True, max_length=500, null=True)),
                ('sales_cess', models.CharField(blank=True, max_length=500, null=True)),
                ('purchase_unit_price', models.CharField(blank=True, max_length=500, null=True)),
                ('puchase_currency', models.CharField(blank=True, max_length=500, null=True)),
                ('purchase_cess', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_name', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('service_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('service_unit', models.CharField(blank=True, max_length=500, null=True)),
                ('service_tax', models.CharField(blank=True, max_length=500, null=True)),
                ('service_sac', models.CharField(blank=True, max_length=500, null=True)),
                ('sales_unit_price', models.CharField(blank=True, max_length=500, null=True)),
                ('sales_currency', models.CharField(blank=True, max_length=500, null=True)),
                ('sales_cess', models.CharField(blank=True, max_length=500, null=True)),
                ('purchase_unit_price', models.CharField(blank=True, max_length=500, null=True)),
                ('puchase_currency', models.CharField(blank=True, max_length=500, null=True)),
                ('purchase_cess', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
