# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-15 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20181215_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastercompany',
            name='company_id',
            field=models.CharField(default=uuid.UUID('ae8db03b-71a3-4db9-abbf-2d2a5b285149'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
