# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-15 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20181215_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastercompany',
            name='company_id',
            field=models.CharField(default=uuid.UUID('dba2b735-97fb-4482-ba34-fbdd6a792b3b'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
