# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-15 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20181215_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cust_sez',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_shipping_gstin',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_type',
        ),
        migrations.AlterField(
            model_name='mastercompany',
            name='company_id',
            field=models.CharField(default=uuid.UUID('c5842de9-cd6b-49aa-81ce-78b2df4cad9f'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
