# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-15 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20181215_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastercompany',
            name='company_id',
        ),
        migrations.AlterField(
            model_name='mastercompany',
            name='company_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
