# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-15 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20181215_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_cess_percent',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_cess_percent',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
