# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-16 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20181215_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Service',
            fields=[
                ('name', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('quantity', models.CharField(blank=True, max_length=500, null=True)),
                ('unit', models.CharField(blank=True, max_length=500, null=True)),
                ('tax', models.CharField(blank=True, max_length=500, null=True)),
                ('hsn', models.CharField(blank=True, max_length=500, null=True)),
                ('sales_unit_price', models.CharField(blank=True, max_length=500, null=True)),
                ('sales_currency', models.CharField(blank=True, max_length=500, null=True)),
                ('sales_cess_percent', models.CharField(blank=True, max_length=500, null=True)),
                ('sales_cess', models.CharField(blank=True, max_length=500, null=True)),
                ('purchase_unit_price', models.CharField(blank=True, max_length=500, null=True)),
                ('puchase_currency', models.CharField(blank=True, max_length=500, null=True)),
                ('purchase_cess_percent', models.CharField(blank=True, max_length=500, null=True)),
                ('purchase_cess', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(blank=True, max_length=500, null=True)),
                ('sac', models.CharField(blank=True, max_length=500, null=True)),
                ('master_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.MasterCompany')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='master_company',
        ),
        migrations.RemoveField(
            model_name='service',
            name='master_company',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
