# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-21 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_tax_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTax',
            fields=[
                ('tax_category', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('master_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.MasterCompany')),
            ],
        ),
        migrations.CreateModel(
            name='UserUnit',
            fields=[
                ('unit_type', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('master_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.MasterCompany')),
            ],
        ),
    ]
