# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-22 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20181222_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('unit', models.CharField(blank=True, max_length=500, null=True)),
                ('quantity', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.CharField(blank=True, max_length=500, null=True)),
                ('discount', models.CharField(blank=True, max_length=500, null=True)),
                ('tax', models.CharField(blank=True, max_length=500, null=True)),
                ('item_total', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('client_name', models.CharField(max_length=500)),
                ('invoice_no', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('invoice_date', models.CharField(blank=True, max_length=500, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=500, null=True)),
                ('po_no', models.CharField(blank=True, max_length=500, null=True)),
                ('due_date', models.CharField(blank=True, max_length=500, null=True)),
                ('shipping_charges', models.CharField(blank=True, max_length=500, null=True)),
                ('waybill_no', models.CharField(blank=True, max_length=500, null=True)),
                ('lr_no', models.CharField(blank=True, max_length=500, null=True)),
                ('challan_no', models.CharField(blank=True, max_length=500, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=500, null=True)),
                ('ship_by', models.CharField(blank=True, max_length=500, null=True)),
                ('transporter_name', models.CharField(blank=True, max_length=500, null=True)),
                ('tansporter_id', models.CharField(blank=True, max_length=500, null=True)),
                ('transporter_gstin', models.CharField(blank=True, max_length=500, null=True)),
                ('terms_conditions', models.CharField(blank=True, max_length=3000, null=True)),
                ('private_notes', models.CharField(blank=True, max_length=3000, null=True)),
                ('total_amount', models.CharField(blank=True, max_length=3000, null=True)),
                ('items', models.ManyToManyField(to='dashboard.Dummy_Product')),
            ],
        ),
    ]
