# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-22 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_dummy_product_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit_Notes',
            fields=[
                ('client_name', models.CharField(max_length=500)),
                ('no', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('date', models.CharField(blank=True, max_length=500, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=500, null=True)),
                ('invoice_date', models.CharField(blank=True, max_length=500, null=True)),
                ('reason', models.CharField(blank=True, max_length=500, null=True)),
                ('shipping_charges', models.CharField(blank=True, max_length=500, null=True)),
                ('terms_conditions', models.CharField(blank=True, max_length=3000, null=True)),
                ('private_notes', models.CharField(blank=True, max_length=3000, null=True)),
                ('total_amount', models.CharField(blank=True, max_length=3000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_Notes',
            fields=[
                ('client_name', models.CharField(max_length=500)),
                ('invoice_no', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('invoice_date', models.CharField(blank=True, max_length=500, null=True)),
                ('po_no', models.CharField(blank=True, max_length=500, null=True)),
                ('due_date', models.CharField(blank=True, max_length=500, null=True)),
                ('waybill_no', models.CharField(blank=True, max_length=500, null=True)),
                ('lr_no', models.CharField(blank=True, max_length=500, null=True)),
                ('challan_no', models.CharField(blank=True, max_length=500, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=500, null=True)),
                ('ship_by', models.CharField(blank=True, max_length=500, null=True)),
                ('transporter_name', models.CharField(blank=True, max_length=500, null=True)),
                ('tansporter_id', models.CharField(blank=True, max_length=500, null=True)),
                ('transporter_gstin', models.CharField(blank=True, max_length=500, null=True)),
                ('terms_conditions', models.CharField(blank=True, max_length=3000, null=True)),
                ('private_notes', models.CharField(blank=True, max_length=3000, null=True)),
                ('total_amount', models.CharField(blank=True, max_length=3000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Order',
            fields=[
                ('client_name', models.CharField(max_length=500)),
                ('no', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('po_date', models.CharField(blank=True, max_length=500, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=500, null=True)),
                ('due_date', models.CharField(blank=True, max_length=500, null=True)),
                ('shipping_charges', models.CharField(blank=True, max_length=500, null=True)),
                ('terms_conditions', models.CharField(blank=True, max_length=3000, null=True)),
                ('private_notes', models.CharField(blank=True, max_length=3000, null=True)),
                ('total_amount', models.CharField(blank=True, max_length=3000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('client_name', models.CharField(max_length=500)),
                ('invoice_no', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('invoice_date', models.CharField(blank=True, max_length=500, null=True)),
                ('po_no', models.CharField(blank=True, max_length=500, null=True)),
                ('due_date', models.CharField(blank=True, max_length=500, null=True)),
                ('shipping_charges', models.CharField(blank=True, max_length=500, null=True)),
                ('terms_conditions', models.CharField(blank=True, max_length=3000, null=True)),
                ('private_notes', models.CharField(blank=True, max_length=3000, null=True)),
                ('total_amount', models.CharField(blank=True, max_length=3000, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='tansporter_id',
            new_name='transporter_id',
        ),
        migrations.AddField(
            model_name='dummy_product',
            name='source',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='quotes',
            name='items',
            field=models.ManyToManyField(to='dashboard.Dummy_Product'),
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='items',
            field=models.ManyToManyField(to='dashboard.Dummy_Product'),
        ),
        migrations.AddField(
            model_name='delivery_notes',
            name='items',
            field=models.ManyToManyField(to='dashboard.Dummy_Product'),
        ),
        migrations.AddField(
            model_name='credit_notes',
            name='items',
            field=models.ManyToManyField(to='dashboard.Dummy_Product'),
        ),
    ]
