# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-22 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20181222_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit_notes',
            name='total_discount',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='credit_notes',
            name='total_tax',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='delivery_notes',
            name='total_discount',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='delivery_notes',
            name='total_tax',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_discount',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_tax',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='total_discount',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='total_tax',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='quotes',
            name='total_discount',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='quotes',
            name='total_tax',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
