# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-22 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20181222_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit_notes',
            name='master_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.MasterCompany'),
        ),
        migrations.AddField(
            model_name='delivery_notes',
            name='master_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.MasterCompany'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='master_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.MasterCompany'),
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='master_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.MasterCompany'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='master_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.MasterCompany'),
        ),
    ]
