# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-22 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20181222_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummy_product',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
