# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-23 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20181223_0535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_order',
            old_name='invoice_no',
            new_name='ref_no',
        ),
    ]
