# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-25 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20181223_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_service',
            name='quantity',
            field=models.IntegerField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product_service',
            name='sales_unit_price',
            field=models.IntegerField(blank=True, max_length=500, null=True),
        ),
    ]
