# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-25 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20181225_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_service',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_service',
            name='sales_unit_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
